import Head from 'next/head'
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.css'
import { useSession } from "next-auth/react"
import { signIn, signOut } from "next-auth/react"

export default function Home() {
  const router = useRouter();
  const { data: session, status } = useSession()

  async function handleOnClick(e) {
    e.preventDefault();
    fetch('/api/twitter/user')
      .then(res => res.json())
      .then(data => {
        if(data.success) {
          // redirect to profile page
          router.push('/by/'+ data.user.username);
        } else {
          if(data.codeMessage === 'EXISTS') {
            // redirect to profile page
            router.push('/by/'+ data.user.username);
          }
        }

      })
      .catch(err => console.log(err))
  } 

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">TwitNest!</a>
        </h1>

        <div className={styles.description}>
        { status === "authenticated" ?
          <>
            Signed in as {session.user.email} <br />
            <button onClick={() => signOut()}>Sign out</button>
          </>
          :
          <>
            Not signed in <br />
            <button onClick={() => signIn("twitter")}>Sign in with Twitter</button>
          </>
        }
        </div>

        <div>
          <button onClick={handleOnClick}>Check Timeline</button>
        </div>
      </main>

      <footer className={styles.footer}>
        TwitNest-App
      </footer>
    </div>
  )
}
