import Head from 'next/head'
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.css'
import { useSession } from "next-auth/react"
import { signIn, signOut } from "next-auth/react"
import React, { useEffect } from 'react';
import Logo from '../components/Logo';


export default function Home() {
  const router = useRouter();
  const { data: session, status } = useSession()

  // Redirect when logged In
  useEffect(() => {
    if (status === "authenticated") {
      router.push("/status")
    }
  }, [status]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      <main className="main">
        <div style={{textAlign:'center'}}>
          <Logo width="200" />
        </div>
        <br />
        <h1 className={styles.title}>
          Welcome to <span style={{color: '#1C9AEF'}}> TwitNest! </span>
        </h1>
        <h2 className={styles.subtitle}>Make your blog from twitter with one click </h2>

        <div className={styles.description}>
        { status === "authenticated" ?
          <>
            Signed in as {session.user.email} <br />
            <button onClick={() => signOut()}>Sign out</button>
          </>
          :
          <>
            <button className={styles.mainBtn} onClick={() => signIn("twitter")}>Sign in with Twitter</button>
          </>
        }
        </div>
      </main>

      <footer className={styles.footer}>
        TwitNest - convert your twitter to blog
      </footer>
    </div>
  )
}
