// Used for first init user and tweet

import Head from 'next/head'
import { useRouter } from 'next/router';
import { useSession } from "next-auth/react"
import React, { useEffect } from 'react';
import Image from 'next/image'
import Link from 'next/link';
import Loading from '../components/Loading';

export default function Home() {
  const router = useRouter();
  const { data: session, status } = useSession()
  const [loadUser, setloadUser] = React.useState(true);
  const [user, setUser] = React.useState(null);
  const [loadPost, setLoadPost] = React.useState(true);
  const [posts, setPosts] = React.useState([]);

  
  // warning it called two times!
  useEffect(() => {
    if(session != null && session != undefined) { 
        fetchProfile()
        initPosts()
    }

    if (!loadPost && !loadUser) {
      router.push('/by/'+ data.user.username);
    }
  }, [session]);


  const fetchProfile = () => {
      // Load User Data from Twitter
      fetch('/api/twitter/user')
      .then(res => res.json())
      .then(data => {
        if(data.success) {
          localStorage.setItem('username', data.user.username)
          setUser(data.user)
          setloadUser(false);
        } else {
          console.log(' error fetching user')
          console.log(data)
        }
    })
  }

  const initPosts = () => {
    console.log('load posts...')
     // Load tweets data
     fetch('/api/twitter/init-tweets')
     .then(res => res.json())
     .then(data => {
       setPosts(data.posts)
       setLoadPost(false)
     }).catch(err => console.log(err))
  }

  if (status === "unauthenticated") {
    return <p>Access Denied. Login first.</p>
  }

  return (
    <div>
      <Head>
        <title>Status Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <main className="main">
      <div>
        {
            loadUser ?
            <div>
                <div>
                    <p>Generating your profile...</p>
                    <Loading />
                </div>
            </div>
            :
            <div>
                <h1>
                    Welcome {user.fullname} !
                </h1>

                <div>
                    <Image
                        className="avatar"
                        src={`${user.profile_image_url.replace('normal', '400x400')}`}
                        alt={`Avatar ${user.username}`}
                        width={80}
                        height={80}
                        />
                    <p> @{user.username} </p>
                    <p> {user.bio} </p>
                    <p> {user.url} </p>
                </div>
            </div>
        }
        
        {
            loadPost &&
            <div>
                <div>
                    <p>Generating your Blog Posts...</p>
                    <Loading />
                </div>
            </div>
           
        }

      {
        (!loadPost && !loadUser) &&
           <div>          
              <p className='info mt-50'> Your Blog is ready! Didn&apos;t believe it? </p>
              <Link href={`/by/${user.username}`}>
                <a className='button'> See your profile</a>
              </Link>
              <p></p>
              <Link href={`/setting`} >
              <a className='button'> Edit Your Blog post</a>
              </Link>   
          </div>
        }
      </div>
     </main>
    </div>
  )
}
